apiVersion: autoscaling.internal.knative.dev/v1alpha1
kind: PodAutoscaler
metadata:
  annotations:
    autoscaling.knative.dev/class: kpa.autoscaling.knative.dev
    autoscaling.knative.dev/metric: concurrency
    serving.knative.dev/creator: kubernetes-admin
  creationTimestamp: "2022-06-28T03:14:03Z"
  generation: 2
  labels:
    app: helloworld-go-00001
    serving.knative.dev/configuration: helloworld-go
    serving.knative.dev/configurationGeneration: "1"
    serving.knative.dev/configurationUID: e4c8ca33-351d-47ce-8765-c06dd61cff50
    serving.knative.dev/revision: helloworld-go-00001
    serving.knative.dev/revisionUID: 722740ff-af00-4df6-a80a-ca4ef31d0307
    serving.knative.dev/service: helloworld-go
    serving.knative.dev/serviceUID: 0c7db8bc-f337-4dd1-93fa-e57e793c975f
  name: helloworld-go-00001
  namespace: default
  ownerReferences:
  - apiVersion: serving.knative.dev/v1
    blockOwnerDeletion: true
    controller: true
    kind: Revision
    name: helloworld-go-00001
    uid: 722740ff-af00-4df6-a80a-ca4ef31d0307
  resourceVersion: "2032933"
  uid: 66555b2e-b3cc-4d99-87da-eab190744a7f
spec:
  protocolType: http1
  reachability: Reachable
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: helloworld-go-00001-deployment
status:
  actualScale: 0
  conditions:
  - lastTransitionTime: "2022-06-28T03:15:09Z"
    message: The target is not receiving traffic.
    reason: NoTraffic
    status: "False"
    type: Active
  - lastTransitionTime: "2022-06-28T03:15:09Z"
    message: The target is not receiving traffic.
    reason: NoTraffic
    status: "False"
    type: Ready
  - lastTransitionTime: "2022-06-28T03:15:09Z"
    message: K8s Service is not ready
    reason: NotReady
    status: Unknown
    type: SKSReady
  - lastTransitionTime: "2022-06-28T03:14:09Z"
    status: "True"
    type: ScaleTargetInitialized
  desiredScale: 0
  metricsServiceName: helloworld-go-00001-private
  observedGeneration: 2
  serviceName: helloworld-go-00001
