apiVersion: serving.knative.dev/v1
kind: Revision
metadata:
  annotations:
    serving.knative.dev/creator: kubernetes-admin
    serving.knative.dev/routes: helloworld-go
    serving.knative.dev/routingStateModified: "2022-06-28T03:14:01Z"
  creationTimestamp: "2022-06-28T03:14:01Z"
  generation: 1
  labels:
    serving.knative.dev/configuration: helloworld-go
    serving.knative.dev/configurationGeneration: "1"
    serving.knative.dev/configurationUID: e4c8ca33-351d-47ce-8765-c06dd61cff50
    serving.knative.dev/routingState: active
    serving.knative.dev/service: helloworld-go
    serving.knative.dev/serviceUID: 0c7db8bc-f337-4dd1-93fa-e57e793c975f
  name: helloworld-go-00001
  namespace: default
  ownerReferences:
  - apiVersion: serving.knative.dev/v1
    blockOwnerDeletion: true
    controller: true
    kind: Configuration
    name: helloworld-go
    uid: e4c8ca33-351d-47ce-8765-c06dd61cff50
  resourceVersion: "2032938"
  uid: 722740ff-af00-4df6-a80a-ca4ef31d0307
spec:
  containerConcurrency: 0
  containers:
  - env:
    - name: TARGET
      value: Go Sample v1.0!
    image: asialeaf/helloworld-go:v1.0
    name: user-container
    readinessProbe:
      successThreshold: 1
      tcpSocket:
        port: 0
    resources: {}
  enableServiceLinks: false
  timeoutSeconds: 300
status:
  actualReplicas: 0
  conditions:
  - lastTransitionTime: "2022-06-28T03:15:10Z"
    message: The target is not receiving traffic.
    reason: NoTraffic
    severity: Info
    status: "False"
    type: Active
  - lastTransitionTime: "2022-06-28T03:14:09Z"
    status: "True"
    type: ContainerHealthy
  - lastTransitionTime: "2022-06-28T03:14:09Z"
    status: "True"
    type: Ready
  - lastTransitionTime: "2022-06-28T03:14:09Z"
    status: "True"
    type: ResourcesAvailable
  containerStatuses:
  - imageDigest: index.docker.io/asialeaf/helloworld-go@sha256:eaff5bda267718c74b3c2fafb74a611fcb55e8d629038dfee890f5080601ed71
    name: user-container
  desiredReplicas: 0
  observedGeneration: 1
